### ISSUE TITLE
Real world image editing

### ISSUE THREAD

**Issue by HyunsooCha** [EnVision-Research/Selective-Diffusion-Distillation#2]
Hi,

Thank you for your excellent work.
I think the current white_hair.yml demo only provides the StyleGAN latent space manipulator example. Is there any way or example for real-world scenarios? It means the input and output of the manipulator are real-world or in-the-wild images, not StyleGAN's latent code.

Thanks in advance.

**Comment by AndysonYs** [comment]
Hi,

Thanks for your question. You can do real-world image editing by using a StyleGAN latent encoder, such as [e4e](https://github.com/omertov/encoder4editing).
